trigger:
  paths:
    exclude:
      - README.md
      - LICENSE
      - .gitignore
      - azure-pipelines.yml

resources:
  - repo: self

pool: "Azure Pipelines"

variables:
  image-repo: 'sdk-example'

stages:
  - stage: BuildAndPush
    displayName: BuildAndPush
    jobs:
      - job: BuildAndPush
        displayName: BuildAndPush

        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'ACR'
              repository: "$(image-repo)"
              command: 'buildAndPush'
              tags: 'latest'
              Dockerfile: '**/Dockerfile'