trigger:
  paths:
    exclude:
      - README.md
      - LICENSE
      - .gitignore
      - azure-pipelines.yml

resources:
  - repo: self

pool: "Azure Pipelines"
#pool: "Default"

variables:
  image-repo: 'bupt2018/sdk-example'

stages:
  - stage: BuildAndPush
    displayName: BuildAndPush
    jobs:
      - job: BuildAndPush
        displayName: BuildAndPush

        steps:
          - task: CmdLine@2
            inputs:
              script: ' x=`echo "$(Build.SourceVersion)" | head -c 8`; echo "##vso[task.setvariable variable=SHORT_COMMIT]$x"'

          - task: Docker@2
            inputs:
              containerRegistry: 'ACR'
              repository: "$(image-repo)"
              command: 'buildAndPush'
              tags: 'latest'
              Dockerfile: '**/Dockerfile'